sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mike2mike/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mike2mike/react-test npm test -- --coverage

after_success:
  - docker build -t mike2mike/multi-client ./client
  - docker build -t mike2mike/multi-nginx ./nginx
  - docker build -t mike2mike/multi-server ./server
  - docker build -t mike2mike/multi-worker ./worker
  # Login
  - echo "$D_PW" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mike2mike/multi-client
  - docker push mike2mike/multi-nginx
  - docker push mike2mike/multi-server
  - docker push mike2mike/multi-worker

deploy:
  provider: elasticbeanstalk
  edge: true
  region: 'eu-west-3'
  app: 'multicon'
  env: 'Multicon-env'
  bucket_name: 'elasticbeanstalk-eu-west-3-208503571711'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
