sudo: required
services:
  - docker

before_install:
  - docker build -t mike2mike/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mike2mike/react-test npm test -- --coverage

after_success:
  - docker build -t mike2mike/multi-client ./client
  - docker build -t mike2mike/multi-nginx ./client
  - docker build -t mike2mike/multi-server ./server
  - docker build -t mike2mike/multi-worker ./worker
